// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKyIlVJkaNA7FC47hubuQouPEputx9PSc',
    appId: '1:825605835009:web:c56303322a6c900f91b300',
    messagingSenderId: '825605835009',
    projectId: 'fcm-app-dna',
    authDomain: 'fcm-app-dna.firebaseapp.com',
    storageBucket: 'fcm-app-dna.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyMb1rABDTaWhLVe1f6BfcNNZEc0deMnY',
    appId: '1:825605835009:android:f83d14ff274fbb2891b300',
    messagingSenderId: '825605835009',
    projectId: 'fcm-app-dna',
    storageBucket: 'fcm-app-dna.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr2995sgn9ZyfDqA270vkdofmaoUOpKKs',
    appId: '1:825605835009:ios:6b2f9bc908ca4a7391b300',
    messagingSenderId: '825605835009',
    projectId: 'fcm-app-dna',
    storageBucket: 'fcm-app-dna.firebasestorage.app',
    iosBundleId: 'com.example.dna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr2995sgn9ZyfDqA270vkdofmaoUOpKKs',
    appId: '1:825605835009:ios:6b2f9bc908ca4a7391b300',
    messagingSenderId: '825605835009',
    projectId: 'fcm-app-dna',
    storageBucket: 'fcm-app-dna.firebasestorage.app',
    iosBundleId: 'com.example.dna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKyIlVJkaNA7FC47hubuQouPEputx9PSc',
    appId: '1:825605835009:web:e2c3969a14329f8a91b300',
    messagingSenderId: '825605835009',
    projectId: 'fcm-app-dna',
    authDomain: 'fcm-app-dna.firebaseapp.com',
    storageBucket: 'fcm-app-dna.firebasestorage.app',
  );
}
